DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
	`no`	INT	NOT NULL AUTO_INCREMENT	COMMENT '회원번호',
	`username`	VARCHAR(100)	NOT NULL	COMMENT '아이디',
	`password`	VARCHAR(100)	NULL	COMMENT '비밀번호',
	`name`	VARCHAR(20)	NOT NULL	COMMENT '이름',
	`email`	VARCHAR(100)	NULL	COMMENT '이메일',
	`enable`	BOOLEAN	NULL	COMMENT '휴면여부',
	`reg_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`upd_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
);

ALTER TABLE `users` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`no`
);
